fix: Update packages.
This fixes an error while building: `semantic error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.`